---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Building


components: 
  schemas: 
    Building: 
      $ref: "https://smart-data-models.github.io/dataModel.Building/Building/model.yaml#/Building"
    Categories: 
      $ref: "https://smart-data-models.github.io/data-models/openstreetmap.yaml#/Categories"
info: 
  description:  |
    This entity contains a harmonised description of a Building. This entity is associated with the vertical segments of smart homes, smart cities, industry and related IoT applications.
    This data model has been partially developed in cooperation with mobile operators and the [GSMA](https://www.gsma.com/iot/iot-big-data/), compared to GSMA data model following changes are introduced:
    -   the reference to `BuildingType` is removed, since `BuildingType` compared to
        `category` attribute does not introduce significant information.

    -   `category` attribute is required.
    -   `openingHours` is introduced following schema.org data model to allow
        fine-grained on building opening times. GSMA supported this as free text in
        the `notes` attribute (removed as well).

    -   `refSubscriptionService` is not supported, since `SubscriptionService` model
        is not supported currently.
  title: Building
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Building
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Building/Building/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Building/Building/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format\n"
    name: ngsi-ld
