--- 
components: 
  schemas: 
    BuildingOperation: 
      $ref: "https://smart-data-models.github.io/dataModel.Building/BuildingOperation/model.yaml#/BuildingOperation"
info: 
  description: |
    This entity contains a harmonised description of a generic operation (related to
    smart buildings) applied to the referenced building. The building operation
    contains dynamic data reported by, or associated with a building or operations
    applicable to the building. This entity is associated with the vertical segments
    of smart homes, smart cities, industry and related IoT applications.
    
    This data model has been partially developed in cooperation with mobile
    operators and the [GSMA](https://www.gsma.com/iot/iot-big-data/), compared to
    GSMA data model the following changes are introduced:
    
    -   `refRelatedDeviceOperation` replaces `refRelatedOperation`
    
    **Note**: JSON Schemas only capture the NGSI simplified representation, this
    means that to test the JSON schema examples with a
    [FIWARE NGSI version 2](http://fiware.github.io/specifications/ngsiv2/stable)
    API implementation, you need to use the `keyValues` mode (`options=keyValues`).
  title: BuildingOperation
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - BuildingOperation
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Building/BuildingOperation/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Building/BuildingOperation/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
